### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by gmshroll** [gmshroll/home-automation#1]
- [ ] endpoint for 'PIR fired' for landing: check landing dimmer state - on or off? If off - bring to 10%, if on, do nothing
- [ ] setup H&T with USB feet, send temperatures to server
- [ ] doorbell signal endpoint: send trigger to FE "watch the front door cam"
- [ ] camera feeds - images or continue to spawn ffmpeg for each cam?
- [ ] front door PIR, light and dimmer - fade up when human detected; down after release
- [ ] ANPR from gate camera
- [ ] gate control (shelly connection)

FE UI
- [ ] standby fade/size (link to wakeup somehow?)
- [ ] standby screen: Clock, temperature 
- [ ] working screen: Tabs (Heating; Lighting and Scenes (all light plans; blinds); Cameras; Access (gate))
- [ ] Heating controls - Nest style desired temp gauge
- [ ] Compatible view for mobile (remote management over vpn)

Heating
- [ ] UI for programming: Hot water programming, on off for each day (grid UI?); Heating programming; on-off for each day (grid UI?)
- [ ] Holiday mode - 10 degrees for 4 hours
- [ ] > desired temp (math.floor)? - switch off
- [ ] < desired temp (math.floor)? - switch on
- [ ] 1 degree movement, preventing rapid switching of boiler

- [ ] VPN

**Comment by gmshroll** [comment]
Shelly dimmers

- [ ] corridor nightlight
-- shelly dimmer on switch circuit; on/off through normal switch
-- PIR sensor(s) in corridor on new switch circuit to sw2

- [ ] doorbell trigger
-- shelly 1

- UI

- [ ] thermostat
-- shelly h&t
-- shelly 2.5

- [ ] front door
-- lighting
-- PIR
-- shelly dimmer

- [ ] Inline extension lead for lamps
-- shelly dimmer

- [ ] blinds
-- somfy blaster
